
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UIAssistant(object):
    def setupUi(self, UIAssistant):
        UIAssistant.setObjectName("UIAssistant")
        UIAssistant.resize(1650, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UIAssistant.sizePolicy().hasHeightForWidth())
        UIAssistant.setSizePolicy(sizePolicy)
        UIAssistant.setMinimumSize(QtCore.QSize(1650, 900))
        UIAssistant.setMaximumSize(QtCore.QSize(1650, 900))
        self.centralwidget = QtWidgets.QWidget(UIAssistant)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_1.setGeometry(QtCore.QRect(-110, -80, 2000, 1000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bg_1.sizePolicy().hasHeightForWidth())
        self.Bg_1.setSizePolicy(sizePolicy)
        self.Bg_1.setMinimumSize(QtCore.QSize(2000, 1000))
        self.Bg_1.setMaximumSize(QtCore.QSize(1600, 900))
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("C:/CODING/c cpp/python programs/AI assistant/project templates/B.G-20231010T154311Z-001/B.G/Black_Template.jpg"))
        self.Bg_1.setScaledContents(True)
        self.Bg_1.setObjectName("Bg_1")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(860, 20, 751, 491))
        self.Gif_2.setStyleSheet("background-color:rgba(0,255,255);")
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("C:/CODING/c cpp/python programs/AI assistant/project templates/ExtraGui-20231010T181648Z-001/ExtraGui/background_gif_2.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_2.setGeometry(QtCore.QRect(10, 10, 731, 521))
        self.Bg_2.setStyleSheet("background-color:rgb(127, 127, 190);")
        self.Bg_2.setText("")
        self.Bg_2.setScaledContents(False)
        self.Bg_2.setObjectName("Bg_2")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(20, 20, 711, 501))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("C:/CODING/c cpp/python programs/AI assistant/project templates/VoiceReg-20231010T154334Z-001/VoiceReg/__02-____.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_time.setGeometry(QtCore.QRect(70, 570, 371, 71))
        self.Text_time.setStyleSheet("background-color:transparent;\n"
"border-radius:none;\n"
"font-size:30px;\n"
"color:rgb(170, 255, 255);\n"
"text-align:center;")
        self.Text_time.setReadOnly(False)
        self.Text_time.setOverwriteMode(True)
        self.Text_time.setObjectName("Text_time")
        self.Bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_3.setGeometry(QtCore.QRect(50, 560, 411, 91))
        self.Bg_3.setText("")
        self.Bg_3.setPixmap(QtGui.QPixmap("C:/CODING/c cpp/python programs/AI assistant/project templates/B.G-20231010T154311Z-001/B.G/neon_rectangle_1.jpg"))
        self.Bg_3.setScaledContents(True)
        self.Bg_3.setObjectName("Bg_3")
        self.Bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_4.setGeometry(QtCore.QRect(50, 700, 411, 91))
        self.Bg_4.setText("")
        self.Bg_4.setPixmap(QtGui.QPixmap("C:/CODING/c cpp/python programs/AI assistant/project templates/B.G-20231010T154311Z-001/B.G/neon_rectangle_1.jpg"))
        self.Bg_4.setScaledContents(True)
        self.Bg_4.setObjectName("Bg_4")
        self.Text_date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_date.setGeometry(QtCore.QRect(70, 710, 371, 71))
        self.Text_date.setStyleSheet("background-color:transparent;\n"
"border-radius:none;\n"
"font-size:30px;\n"
"color:rgb(170, 255, 255);\n"
"text-align:center;")
        self.Text_date.setReadOnly(False)
        self.Text_date.setOverwriteMode(True)
        self.Text_date.setObjectName("Text_date")
        self.Start_button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_button.setGeometry(QtCore.QRect(880, 570, 231, 61))
        self.Start_button.setStyleSheet("background-color:transparent;\n"
"color:rgb(170, 255, 255);\n"
"border-radius:none;\n"
"font-size:20px;")
        self.Start_button.setObjectName("Start_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(830, 560, 321, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/CODING/c cpp/python programs/AI assistant/project templates/B.G-20231010T154311Z-001/B.G/6518962.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1250, 560, 321, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/CODING/c cpp/python programs/AI assistant/project templates/B.G-20231010T154311Z-001/B.G/6518962.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.STop_button = QtWidgets.QPushButton(self.centralwidget)
        self.STop_button.setGeometry(QtCore.QRect(1290, 570, 231, 61))
        self.STop_button.setStyleSheet("background-color:transparent;\n"
"color:rgb(170, 255, 255);\n"
"border-radius:none;\n"
"font-size:20px;")
        self.STop_button.setObjectName("STop_button")
        self.Bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_5.setGeometry(QtCore.QRect(850, 10, 771, 511))
        self.Bg_5.setStyleSheet("background-color:rgb(127, 127, 190);")
        self.Bg_5.setText("")
        self.Bg_5.setScaledContents(False)
        self.Bg_5.setObjectName("Bg_5")
        self.Bg_1.raise_()
        self.Bg_2.raise_()
        self.Gif_1.raise_()
        self.Bg_3.raise_()
        self.Text_time.raise_()
        self.Bg_4.raise_()
        self.Text_date.raise_()
        self.label.raise_()
        self.Start_button.raise_()
        self.label_2.raise_()
        self.STop_button.raise_()
        self.Bg_5.raise_()
        self.Gif_2.raise_()
        UIAssistant.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UIAssistant)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1650, 26))
        self.menubar.setObjectName("menubar")
        UIAssistant.setMenuBar(self.menubar)

        self.retranslateUi(UIAssistant)
        QtCore.QMetaObject.connectSlotsByName(UIAssistant)

    def retranslateUi(self, UIAssistant):
        _translate = QtCore.QCoreApplication.translate
        UIAssistant.setWindowTitle(_translate("UIAssistant", "MainWindow"))
        self.Start_button.setText(_translate("UIAssistant", "Start"))
        self.STop_button.setText(_translate("UIAssistant", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UIAssistant = QtWidgets.QMainWindow()
    ui = Ui_UIAssistant()
    ui.setupUi(UIAssistant)
    UIAssistant.show()
    sys.exit(app.exec_())
